#The routine that randomly chooses a player to troll
scheduler: 
    #How often to troll (in ticks) false=disable
    frequency: 200

#The routine that determines which players can get trolled
players:
    #A list of all players that cannot be trolled, seperated by commas
    blacklist: [player1,player2]
    #Whether the whitelist or blacklist can be overriden by the -override flag
    can-override: true

#A list of all possible trolls
trolls:
    #Spawns live tnt at the player
    tnt: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The length (in ticks) of the fuse
            fuse-length: 25
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Plays the creeper fuse sound to the player
    creepscare:
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The volume of the sound 10=normal
            volume: 10
            #The pitch of the sound 1=normal
            pitch: 1
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Strikes the player with lightning
    lightning: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Sets the player on fire
    fire: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How long (in ticks) to apply the effect for 20=1 second
            ticks: 100
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Changes the players walkspeed
    speed: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The new speed to give the player 0.2=normal -1.0=can only move while jumping
            newspeed: -1.0
            #How long (in ticks) to apply the effect for 20=1 second
            ticks: 600
            #How likely it is that the scheduler will choose this troll 1=often 0.5=sometimes 0=never
            likelyness: 0.5
    #Causes the player's screen to wobble as though drunk
    drunk: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How long (in ticks) to apply the effect for 20=1 second
            ticks: 600
            #The amplitude of the effect (1=normal)
            amplitude: 1
            #Whether or not to apply the effect to players around the target as well 1=yes false=no
            ambient: false
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Deletes blocks above the player, then teleports them up
    up: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How many blocks upwards to go
            blocks: 16
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Deletes blocks below the player, causing them to fall
    down: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How many blocks downwards to delete
            blocks: 16
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Changes the value of the players hunger bar
    hungry: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The player's new hunger value
            newhunger: 0
            #The player's new saturation value
            newsaturation: 0
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Drops whatever item the player is currently holding
    drop: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #Whether or not to drop the items back into the world true=drop false=destroy
            intoworld: true
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Slows the players mining speed
    fatigue: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How long (in ticks) to apply the effect for 20=1 second
            ticks: 600
            #The amplitude of the effect (1=normal)
            amplitude: 10
            #Whether or not to apply the effect to players near the target
            ambient: false
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Spawns a cube of gravel above the player
    gravel: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The size (in blocks) of the cube (3 = 3x3x3)
            size: 3
            #How high (in blocks) above the players head to spawn the cube
            height: 2
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Spawns chickens at the players current location
    chickens: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How many chickens to spawn(WARNING: Over 50 will probably lag the client, over 100 will likely lag the server, over 250 is just a bad idea! Use at your own risk)
            amount: 10
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Digs a hole around the player and fills it with water
    water: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The size (in blocks) of the hole (3=3x3x3)
            size: 5
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Surrounds the player with a cube of blocks
    entomb: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Plays the ghast screech to the player
    ghastscare: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The volume of the sound (10=normal)
            volume: 10
            #The pitch of the sound (1=normal)
            pitch: 1
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Deals damage to the player
    hurt: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The damage to inflict upon the target (2=1 heart)
            damage: 2
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Replaces the player's whole inventory
    replace: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #If the player is underwater, changes thier remaining air value
    air: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The new air amount to give the player (0=no air left)
            newair: 0
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Poisons the player
    poison: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The amplitude of the effect (1=normal)
            amplitude: 1
            #Whether or not to apply the effect to players near the target
            ambient: false
            #How long (in ticks) to apply the effect for 20=1 second
            ticks: 120
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Shows night time on the players client, regardless of the current server time
    night: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How long (in ticks) to apply the effect for 20=1 second
            ticks: 6000
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Shows rain on the players client, regardless of the current server weather
    rain: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How long (in ticks) to apply the effect for 20=1 second
            ticks: 6000
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Makes the player say things in chat
    chat: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The list of possible messages to send (seperated by commas, eg: [I just got trolled, REKT]
            messages: [I just got trolled, I just got REKT]
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Blinds the player
    blind: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How long (in ticks) to apply the effect for 20=1 second
            ticks: 400
            #Whether or not to apply the effect to players near the target
            ambient: false
            #The amplitude of the effect (1=normal)
            amplitude: 1
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Weakens the players attack
    weakness: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How long (in ticks) to apply the effect for 20=1 second
            ticks: 2400
            #Whether or not to apply the effect to players near the target
            ambient: false
            #The amplitude of the effect (1=normal)
            amplitude: 2
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Adds the wither effect to the player
    wither: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How long (in ticks) to apply the effect for 20=1 second
            ticks: 300
            #Whether or not to apply the effect to players near the target
            ambient: false
            #The amplitude of the effect (1=normal)
            amplitude: 1
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Adds the slow effect to the player
    slow: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How long (in ticks) to apply the effect for 20=1 second
            ticks: 2400
            #Whether or not to apply the effect to players near the target
            ambient: false
            #The amplitude of the effect (1=normal)
            amplitude: 2
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Creates an explosion at the player's bed
    bedsplode: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How large the explosion is (4.0=normal tnt)
            yield: 6.5
            #Whether or not the explosion sets fires (true=yes false=no)
            fire: false
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Changes the location that the players compass points to
    compass: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #How far (in blocks) to set the new compass location from the original
            distance: 1000
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Changes the players level
    level: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #The new level to give the player
            newlevel: 1
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5
    #Scans for torches around the player and deletes them
    torch: 
        #Whether or not to allow this troll
        allow: true
        #Whether or not allow parameter can be overridden by the -override flag
        can-override: true
        #The list of parameters for this troll
        parameters: 
            #Whether or not the torches explode when they disappear
            explode: true
            #The yield of the explosion (suggested to be small, eg(0.25)
            yield: 0.25
            #How far (in blocks) from the target to scan for torches
            range: 20
            #How likely it is that the scheduler will choose this troll 1=often 0=never
            likelyness: 0.5