scheduler: 
    frequency: 
    exact:

announcement:
    announce: 
    public-announce: 
    announce-manual: 
    public-announce-manual: 

logging: 
    log: 
    log-parameters: 
    log-locations: 
    log-manual: 

players:
    whitelist: []
    blacklist: []
    can-override: 

trolls:
    tnt: 
        allow:
        can-override: 
        parameters: 
            yield: 
            set-fires: 
            likelyness: 
    creepscare:
        allow: 
        can-override: 
        parameters: 
            volume: 
            ambient: 
            pitch: 
    lightning: 
        allow: 
        can-override: 
        parameters: 
            set-fire: 
    fire: 
        allow: 
        can-override: 
        parameters: 
            ticks: 
    speed: 
        allow: 
        can-override: 
        parameters: 
            newspeed: 
            ticks: 
    drunk: 
        allow: 
        can-override: 
        parameters: 
            ticks: 
            amplitude: 
            ambient: 
    up: 
        allow: 
        can-override: 
        parameters: 
            blocks: 
        
    down: 
        allow: 
        can-override: 
        parameters: 
            blocks:
            infront: 
    hungry: 
        allow: 
        can-override: 
        parameters: 
            newhunger: 
            newsaturation: 
    drop: 
        allow: 
        can-override: 
        parameters: 
            intoworld: 
            distance: 
    fatigue: 
        allow: 
        can-override: 
        parameters: 
            ticks: 
            amplitude: 
            ambient: 
    gravel: 
        allow: 
        can-override: 
        parameters: 
            size: 
            height: 
    chickens: 
        allow: 
        can-override: 
        parameters: 
            amount: 
            ticks: 
    water: 
        allow: 
        can-override: 
        parameters: 
            depth: 
            size: 
            pour: 
    entomb: 
        allow: 
        can-override: 
        parameters: 
            thickness: 
            material: 
    ghastscare: 
        allow: 
        can-override: 
        parameters: 
            volume: 
            ambient: 
            pitch: 
            onlynether: 
    fireball: 
        allow: 
        can-override: 
        parameters: 
            yield: 
            onlynether: 
            distance: 
    arrow: 
        allow: 
        can-override: 
        parameters: 
            distance: 
            spread: 
            speed: 
    hurt: 
        allow: 
        can-override: 
        parameters: 
            damage: 
            ambient: 
    replace: 
        allow: 
        can-override: 
        parameters: 
            material: 
            amount: 
            chest: 
    herobrine: 
        allow: 
        can-override: 
        parameters: 
            messages: []
            color: 
    namechange: 
        allow: 
        can-override: 
        parameters: 
            newname: 
    air: 
        allow: 
        can-override: 
        parameters: 
            newair: 
    poison: 
        allow: 
        can-override: 
        parameters: 
            amplitude: 
            ambient: 
            ticks: 
    night: 
        allow: 
        can-override: 
        parameters: 
            ticks: 
    rain: 
        allow: 
        can-override: 
        parameters: 
            ticks: 
    chat: 
        allow: 
        can-override: 
        parameters: 
            messages: []
    blind: 
        allow: 
        can-override: 
        parameters: 
            ticks: 
            ambient: 
            amplitude: 
    weakness: 
        allow: 
        can-override: 
        parameters: 
            ticks: 
            ambient: 
            amplitude: 
    wither: 
        allow: 
        can-override: 
        parameters: 
            ticks: 
            ambient: 
            amplitude: 
    slow: 
        allow: 
        can-override: 
        parameters: 
            ticks: 
            ambient: 
            amplitude: 
    bedsplode: 
        allow: 
        can-override: 
        parameters: 
            yield: 
            fire: 
    compass: 
        allow: 
        can-override: 
        parameters: 
            distance: 
    level: 
        allow: 
        can-override: 
        parameters: 
            newlevel: 
    torch: 
        allow: 
        can-override: 
        parameters: 
         explode: 
         yield: 
         range: 