name: Troll Em
main: frostbyte.plugins.trollem.TrollEm
version: 1.0b
description: Subtley trolls players on a regular basis
authors: [_FrostByte_]
website: http://dev.bukkit.org/bukkit-plugins/troll-em/
permissions:
    trollem.troll:
        description: Permission for 'troll' command
        default: op
commands:
    troll:
        description: Trolls people hardcore
        permission: trollem.troll
        usage: troll [PlayerName] <TrollType>
        permission-message: Nice try, GumGum! You need permission to use that command